### PR TITLE
Fix bugs from last PR :(

### PR DESCRIPTION
**Pull request by rogerhutchings**
cc @simoneduca

### CODE REVIEW

**Comment by simoneduca** [comment]
Paths to login/logout buttons also need fixing. I'll push if you don't mind

**Review by simoneduca — APPROVED** [review]
Everything is in order now, thanks.

**Comment by shaunanoordin** [comment]
Ah, OK! This explains why I couldn't get my remove-commonJS-modules branch running. Good catch - I'm also encountering `ERROR: can't resolve AuthContainer` on my end

**Comment by simoneduca** [comment]
Should be sorted now @shaunanoordin, right?

**Comment by shaunanoordin** [comment]
@simoneduca Yeah, I posted that about the same second you pushed the PR fix.

**Pull request merged**
